name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ENCODED_EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.38.25.129 << 'EOF'
          cd /home/ubuntu/codeplanner/Codeplanner_Frontend
          git pull origin main

          rm -rf .next node_modules
          npm install
          npm run build:prod

          pm2 delete codeplanner-frontend || true
          pm2 start ecosystem.config.js --env production

          sudo nginx -t && sudo systemctl reload nginx

          echo "✅ Frontend deployment complete"
        EOF
